//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.03 at 02:04:24 PM CEST 
//


package af.jstech.migration.jaxb.scheduler;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Commands complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Commands">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}add_jobs"/>
 *         &lt;element ref="{}add_order"/>
 *         &lt;element name="check_folders" type="{}check_folders"/>
 *         &lt;element ref="{}kill_task"/>
 *         &lt;element ref="{}licence.use"/>
 *         &lt;element name="lock" type="{}lock"/>
 *         &lt;element name="lock.remove" type="{}lock.remove"/>
 *         &lt;element ref="{}modify_job"/>
 *         &lt;element ref="{}modify_hot_folder"/>
 *         &lt;element ref="{}modify_order"/>
 *         &lt;element ref="{}modify_spooler"/>
 *         &lt;element ref="{}job.why"/>
 *         &lt;element ref="{}job_chain.modify"/>
 *         &lt;element ref="{}job_chain_node.modify"/>
 *         &lt;element name="order" type="{}order"/>
 *         &lt;element ref="{}plugin.command"/>
 *         &lt;element name="process_class" type="{}process_class"/>
 *         &lt;element name="process_class.remove" type="{}process_class.remove"/>
 *         &lt;element ref="{}register_remote_scheduler"/>
 *         &lt;element ref="{}remove_job_chain"/>
 *         &lt;element ref="{}remove_order"/>
 *         &lt;element name="run_time" type="{}run_time"/>
 *         &lt;element ref="{}scheduler_log.log_categories.reset"/>
 *         &lt;element ref="{}scheduler_log.log_categories.set"/>
 *         &lt;element ref="{}scheduler_log.log_categories.show"/>
 *         &lt;element ref="{}show_calendar"/>
 *         &lt;element ref="{}show_history"/>
 *         &lt;element ref="{}show_job"/>
 *         &lt;element ref="{}show_jobs"/>
 *         &lt;element ref="{}show_job_chains"/>
 *         &lt;element ref="{}show_job_chain"/>
 *         &lt;element ref="{}show_order"/>
 *         &lt;element ref="{}s"/>
 *         &lt;element ref="{}show_schedulers"/>
 *         &lt;element ref="{}show_state"/>
 *         &lt;element ref="{}show_task"/>
 *         &lt;element ref="{}service_request"/>
 *         &lt;element ref="{}start_job"/>
 *         &lt;element ref="{}subsystem.show"/>
 *         &lt;element ref="{}remote_scheduler.start_remote_task"/>
 *         &lt;element ref="{}remote_scheduler.remote_task.close"/>
 *         &lt;element ref="{}terminate"/>
 *       &lt;/choice>
 *       &lt;attribute name="on_exit_code">
 *         &lt;simpleType>
 *           &lt;union>
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                 &lt;enumeration value="success"/>
 *                 &lt;enumeration value="error"/>
 *                 &lt;enumeration value="signal"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *             &lt;simpleType>
 *               &lt;list>
 *                 &lt;simpleType>
 *                   &lt;union memberTypes=" {http://www.w3.org/2001/XMLSchema}integer {}Unix_signal_name">
 *                   &lt;/union>
 *                 &lt;/simpleType>
 *               &lt;/list>
 *             &lt;/simpleType>
 *           &lt;/union>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Commands", propOrder = {
    "addJobsOrAddOrderOrCheckFolders"
})
public class Commands {

    @XmlElementRefs({
        @XmlElementRef(name = "show_state", type = JAXBElement.class),
        @XmlElementRef(name = "subsystem.show", type = JAXBElement.class),
        @XmlElementRef(name = "process_class", type = JAXBElement.class),
        @XmlElementRef(name = "start_job", type = StartJob.class),
        @XmlElementRef(name = "service_request", type = ServiceRequest.class),
        @XmlElementRef(name = "scheduler_log.log_categories.show", type = JAXBElement.class),
        @XmlElementRef(name = "modify_order", type = ModifyOrder.class),
        @XmlElementRef(name = "remove_order", type = RemoveOrder.class),
        @XmlElementRef(name = "show_job_chains", type = ShowJobChains.class),
        @XmlElementRef(name = "show_job", type = ShowJob.class),
        @XmlElementRef(name = "modify_hot_folder", type = JAXBElement.class),
        @XmlElementRef(name = "remote_scheduler.remote_task.close", type = RemoteSchedulerRemoteTaskClose.class),
        @XmlElementRef(name = "scheduler_log.log_categories.set", type = SchedulerLogLogCategoriesSet.class),
        @XmlElementRef(name = "show_order", type = ShowOrder.class),
        @XmlElementRef(name = "add_jobs", type = AddJobs.class),
        @XmlElementRef(name = "add_order", type = JAXBElement.class),
        @XmlElementRef(name = "remove_job_chain", type = RemoveJobChain.class),
        @XmlElementRef(name = "job.why", type = JobWhy.class),
        @XmlElementRef(name = "remote_scheduler.start_remote_task", type = RemoteSchedulerStartRemoteTask.class),
        @XmlElementRef(name = "register_remote_scheduler", type = RegisterRemoteScheduler.class),
        @XmlElementRef(name = "lock", type = JAXBElement.class),
        @XmlElementRef(name = "show_task", type = ShowTask.class),
        @XmlElementRef(name = "kill_task", type = KillTask.class),
        @XmlElementRef(name = "job_chain.modify", type = JobChainModify.class),
        @XmlElementRef(name = "plugin.command", type = PluginCommand.class),
        @XmlElementRef(name = "modify_spooler", type = ModifySpooler.class),
        @XmlElementRef(name = "show_job_chain", type = ShowJobChain.class),
        @XmlElementRef(name = "s", type = JAXBElement.class),
        @XmlElementRef(name = "modify_job", type = ModifyJob.class),
        @XmlElementRef(name = "process_class.remove", type = JAXBElement.class),
        @XmlElementRef(name = "show_history", type = ShowHistory.class),
        @XmlElementRef(name = "show_schedulers", type = JAXBElement.class),
        @XmlElementRef(name = "show_calendar", type = ShowCalendar.class),
        @XmlElementRef(name = "terminate", type = Terminate.class),
        @XmlElementRef(name = "show_jobs", type = ShowJobs.class),
        @XmlElementRef(name = "check_folders", type = JAXBElement.class),
        @XmlElementRef(name = "licence.use", type = LicenceUse.class),
        @XmlElementRef(name = "order", type = JAXBElement.class),
        @XmlElementRef(name = "lock.remove", type = JAXBElement.class),
        @XmlElementRef(name = "job_chain_node.modify", type = JobChainNodeModify.class),
        @XmlElementRef(name = "scheduler_log.log_categories.reset", type = SchedulerLogLogCategoriesReset.class),
        @XmlElementRef(name = "run_time", type = JAXBElement.class)
    })
    protected List<Object> addJobsOrAddOrderOrCheckFolders;
    @XmlAttribute(name = "on_exit_code")
    protected List<String> onExitCode;

    /**
     * Gets the value of the addJobsOrAddOrderOrCheckFolders property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addJobsOrAddOrderOrCheckFolders property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddJobsOrAddOrderOrCheckFolders().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ShowState }{@code >}
     * {@link JAXBElement }{@code <}{@link ProcessClass }{@code >}
     * {@link JAXBElement }{@code <}{@link SubsystemShow }{@code >}
     * {@link StartJob }
     * {@link ServiceRequest }
     * {@link RemoveOrder }
     * {@link ModifyOrder }
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link ShowJobChains }
     * {@link ShowJob }
     * {@link RemoteSchedulerRemoteTaskClose }
     * {@link JAXBElement }{@code <}{@link ModifyHotFolder }{@code >}
     * {@link SchedulerLogLogCategoriesSet }
     * {@link ShowOrder }
     * {@link AddJobs }
     * {@link JAXBElement }{@code <}{@link Order }{@code >}
     * {@link RemoveJobChain }
     * {@link JobWhy }
     * {@link RemoteSchedulerStartRemoteTask }
     * {@link RegisterRemoteScheduler }
     * {@link JAXBElement }{@code <}{@link Lock }{@code >}
     * {@link ShowTask }
     * {@link JobChainModify }
     * {@link KillTask }
     * {@link PluginCommand }
     * {@link ModifySpooler }
     * {@link JAXBElement }{@code <}{@link ShowState }{@code >}
     * {@link ShowJobChain }
     * {@link ModifyJob }
     * {@link ShowHistory }
     * {@link JAXBElement }{@code <}{@link ProcessClassRemove }{@code >}
     * {@link JAXBElement }{@code <}{@link ShowState }{@code >}
     * {@link Terminate }
     * {@link ShowCalendar }
     * {@link ShowJobs }
     * {@link JAXBElement }{@code <}{@link CheckFolders }{@code >}
     * {@link LicenceUse }
     * {@link JAXBElement }{@code <}{@link Order }{@code >}
     * {@link JAXBElement }{@code <}{@link LockRemove }{@code >}
     * {@link JobChainNodeModify }
     * {@link SchedulerLogLogCategoriesReset }
     * {@link JAXBElement }{@code <}{@link RunTime }{@code >}
     * 
     * 
     */
    public List<Object> getAddJobsOrAddOrderOrCheckFolders() {
        if (addJobsOrAddOrderOrCheckFolders == null) {
            addJobsOrAddOrderOrCheckFolders = new ArrayList<Object>();
        }
        return this.addJobsOrAddOrderOrCheckFolders;
    }

    /**
     * Gets the value of the onExitCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onExitCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnExitCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOnExitCode() {
        if (onExitCode == null) {
            onExitCode = new ArrayList<String>();
        }
        return this.onExitCode;
    }

}
