//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.03 at 02:04:24 PM CEST 
//


package af.jstech.migration.jaxb.scheduler;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for http_server element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="http_server">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="http.authentication" type="{}http.authentication"/>
 *           &lt;element name="web_service" type="{}web_service"/>
 *           &lt;element name="http_directory" type="{}http_directory"/>
 *         &lt;/choice>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "httpAuthenticationOrWebServiceOrHttpDirectory"
})
@XmlRootElement(name = "http_server")
public class HttpServer {

    @XmlElements({
        @XmlElement(name = "web_service", required = true, type = WebService.class),
        @XmlElement(name = "http_directory", required = true, type = HttpDirectory.class),
        @XmlElement(name = "http.authentication", required = true, type = HttpAuthentication.class)
    })
    protected List<Object> httpAuthenticationOrWebServiceOrHttpDirectory;

    /**
     * Gets the value of the httpAuthenticationOrWebServiceOrHttpDirectory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the httpAuthenticationOrWebServiceOrHttpDirectory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHttpAuthenticationOrWebServiceOrHttpDirectory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WebService }
     * {@link HttpDirectory }
     * {@link HttpAuthentication }
     * 
     * 
     */
    public List<Object> getHttpAuthenticationOrWebServiceOrHttpDirectory() {
        if (httpAuthenticationOrWebServiceOrHttpDirectory == null) {
            httpAuthenticationOrWebServiceOrHttpDirectory = new ArrayList<Object>();
        }
        return this.httpAuthenticationOrWebServiceOrHttpDirectory;
    }

}
