//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.03 at 02:04:24 PM CEST 
//


package af.jstech.migration.jaxb.scheduler;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import af.jstech.migration.jaxb.scheduler.Job.DelayAfterError;
import af.jstech.migration.jaxb.scheduler.Job.DelayOrderAfterSetback;
import af.jstech.migration.jaxb.scheduler.Job.Description;
import af.jstech.migration.jaxb.scheduler.Job.LockUse;
import af.jstech.migration.jaxb.scheduler.Job.Monitor;
import af.jstech.migration.jaxb.scheduler.Job.Process;
import af.jstech.migration.jaxb.scheduler.Job.StartWhenDirectoryChanged;


/**
 * <p>Java class for job element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="job">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="settings" type="{}Job.Settings" minOccurs="0"/>
 *           &lt;element name="description" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element ref="{}include"/>
 *                   &lt;/choice>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="lock.use" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="exclusive" type="{}Yes_no" />
 *                   &lt;attribute name="lock" use="required" type="{}String" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element ref="{}params" minOccurs="0"/>
 *           &lt;element name="environment" type="{}environment" minOccurs="0"/>
 *           &lt;choice minOccurs="0">
 *             &lt;element ref="{}script"/>
 *             &lt;element name="process">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;sequence>
 *                       &lt;element name="environment" type="{}environment" minOccurs="0"/>
 *                     &lt;/sequence>
 *                     &lt;attribute name="file" use="required" type="{}File" />
 *                     &lt;attribute name="ignore_error" type="{}Yes_no" />
 *                     &lt;attribute name="ignore_signal" type="{}Yes_no" />
 *                     &lt;attribute name="log_file" type="{}File" />
 *                     &lt;attribute name="param" type="{}String" />
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *           &lt;/choice>
 *           &lt;element name="monitor" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{}script"/>
 *                   &lt;/sequence>
 *                   &lt;attribute name="name" type="{}Name" />
 *                   &lt;attribute name="ordering" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="start_when_directory_changed" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="directory" use="required" type="{}File" />
 *                   &lt;attribute name="regex" type="{}String" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="delay_after_error" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="delay" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{}String">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                   &lt;attribute name="error_count" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="delay_order_after_setback" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="delay" type="{}Duration" />
 *                   &lt;attribute name="is_maximum" type="{}Yes_no" />
 *                   &lt;attribute name="setback_count" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="run_time" type="{}run_time" minOccurs="0"/>
 *           &lt;element name="commands" type="{}Commands" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="enabled" type="{}Yes_no" />
 *         &lt;attribute name="force_idle_timeout" type="{}Yes_no" />
 *         &lt;attribute name="idle_timeout" type="{}Duration_or_never" />
 *         &lt;attribute name="ignore_signals">
 *           &lt;simpleType>
 *             &lt;union>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                   &lt;enumeration value="all"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *               &lt;simpleType>
 *                 &lt;list itemType="{}Unix_signal" />
 *               &lt;/simpleType>
 *             &lt;/union>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *         &lt;attribute name="java_options" type="{}String" />
 *         &lt;attribute name="log_append" type="{}Yes_no" />
 *         &lt;attribute name="mail_xslt_stylesheet" type="{}File" />
 *         &lt;attribute name="min_tasks" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *         &lt;attribute name="name" type="{}Name" />
 *         &lt;attribute name="order" type="{}Yes_no" />
 *         &lt;attribute name="priority" type="{}Process_priority" />
 *         &lt;attribute name="process_class" type="{}Path" />
 *         &lt;attribute name="replace" type="{}Yes_no" />
 *         &lt;attribute name="separate_process" type="{}Yes_no" />
 *         &lt;attribute name="spooler_id" type="{}Name" />
 *         &lt;attribute name="stop_on_error" type="{}Yes_no" />
 *         &lt;attribute name="tasks" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *         &lt;attribute name="temporary" type="{}Yes_no" />
 *         &lt;attribute name="timeout" type="{}Duration" />
 *         &lt;attribute name="title" type="{}String" />
 *         &lt;attribute name="visible" type="{}Yes_no_never" />
 *         &lt;attribute name="warn_if_longer_than" type="{}Duration_or_percentage" />
 *         &lt;attribute name="warn_if_shorter_than" type="{}Duration_or_percentage" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "settings",
    "description",
    "lockUse",
    "params",
    "environment",
    "script",
    "process",
    "monitor",
    "startWhenDirectoryChanged",
    "delayAfterError",
    "delayOrderAfterSetback",
    "runTime",
    "commands"
})
@XmlRootElement(name = "job")
public class Job {

    protected JobSettings settings;
    protected Description description;
    @XmlElement(name = "lock.use", required = true)
    protected List<LockUse> lockUse;
    protected Params params;
    protected Environment environment;
    protected Script script;
    protected Process process;
    @XmlElement(required = true)
    protected List<Monitor> monitor;
    @XmlElement(name = "start_when_directory_changed", required = true)
    protected List<StartWhenDirectoryChanged> startWhenDirectoryChanged;
    @XmlElement(name = "delay_after_error", required = true)
    protected List<DelayAfterError> delayAfterError;
    @XmlElement(name = "delay_order_after_setback", required = true)
    protected List<DelayOrderAfterSetback> delayOrderAfterSetback;
    @XmlElement(name = "run_time")
    protected RunTime runTime;
    @XmlElement(required = true)
    protected List<Commands> commands;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String enabled;
    @XmlAttribute(name = "force_idle_timeout")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String forceIdleTimeout;
    @XmlAttribute(name = "idle_timeout")
    protected String idleTimeout;
    @XmlAttribute(name = "ignore_signals")
    protected List<String> ignoreSignals;
    @XmlAttribute(name = "java_options")
    protected String javaOptions;
    @XmlAttribute(name = "log_append")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String logAppend;
    @XmlAttribute(name = "mail_xslt_stylesheet")
    protected String mailXsltStylesheet;
    @XmlAttribute(name = "min_tasks")
    protected BigInteger minTasks;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String order;
    @XmlAttribute
    protected List<String> priority;
    @XmlAttribute(name = "process_class")
    protected String processClass;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String replace;
    @XmlAttribute(name = "separate_process")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String separateProcess;
    @XmlAttribute(name = "spooler_id")
    protected String spoolerId;
    @XmlAttribute(name = "stop_on_error")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String stopOnError;
    @XmlAttribute
    protected BigInteger tasks;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String temporary;
    @XmlAttribute
    protected String timeout;
    @XmlAttribute
    protected String title;
    @XmlAttribute
    protected String visible;
    @XmlAttribute(name = "warn_if_longer_than")
    protected String warnIfLongerThan;
    @XmlAttribute(name = "warn_if_shorter_than")
    protected String warnIfShorterThan;

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link JobSettings }
     *     
     */
    public JobSettings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobSettings }
     *     
     */
    public void setSettings(JobSettings value) {
        this.settings = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the lockUse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lockUse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLockUse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LockUse }
     * 
     * 
     */
    public List<LockUse> getLockUse() {
        if (lockUse == null) {
            lockUse = new ArrayList<LockUse>();
        }
        return this.lockUse;
    }

    /**
     * Gets the value of the params property.
     * 
     * @return
     *     possible object is
     *     {@link Params }
     *     
     */
    public Params getParams() {
        return params;
    }

    /**
     * Sets the value of the params property.
     * 
     * @param value
     *     allowed object is
     *     {@link Params }
     *     
     */
    public void setParams(Params value) {
        this.params = value;
    }

    /**
     * Gets the value of the environment property.
     * 
     * @return
     *     possible object is
     *     {@link Environment }
     *     
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * Sets the value of the environment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Environment }
     *     
     */
    public void setEnvironment(Environment value) {
        this.environment = value;
    }

    /**
     * Gets the value of the script property.
     * 
     * @return
     *     possible object is
     *     {@link Script }
     *     
     */
    public Script getScript() {
        return script;
    }

    /**
     * Sets the value of the script property.
     * 
     * @param value
     *     allowed object is
     *     {@link Script }
     *     
     */
    public void setScript(Script value) {
        this.script = value;
    }

    /**
     * Gets the value of the process property.
     * 
     * @return
     *     possible object is
     *     {@link Process }
     *     
     */
    public Process getProcess() {
        return process;
    }

    /**
     * Sets the value of the process property.
     * 
     * @param value
     *     allowed object is
     *     {@link Process }
     *     
     */
    public void setProcess(Process value) {
        this.process = value;
    }

    /**
     * Gets the value of the monitor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the monitor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMonitor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Monitor }
     * 
     * 
     */
    public List<Monitor> getMonitor() {
        if (monitor == null) {
            monitor = new ArrayList<Monitor>();
        }
        return this.monitor;
    }

    /**
     * Gets the value of the startWhenDirectoryChanged property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the startWhenDirectoryChanged property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStartWhenDirectoryChanged().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StartWhenDirectoryChanged }
     * 
     * 
     */
    public List<StartWhenDirectoryChanged> getStartWhenDirectoryChanged() {
        if (startWhenDirectoryChanged == null) {
            startWhenDirectoryChanged = new ArrayList<StartWhenDirectoryChanged>();
        }
        return this.startWhenDirectoryChanged;
    }

    /**
     * Gets the value of the delayAfterError property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delayAfterError property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelayAfterError().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DelayAfterError }
     * 
     * 
     */
    public List<DelayAfterError> getDelayAfterError() {
        if (delayAfterError == null) {
            delayAfterError = new ArrayList<DelayAfterError>();
        }
        return this.delayAfterError;
    }

    /**
     * Gets the value of the delayOrderAfterSetback property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delayOrderAfterSetback property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelayOrderAfterSetback().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DelayOrderAfterSetback }
     * 
     * 
     */
    public List<DelayOrderAfterSetback> getDelayOrderAfterSetback() {
        if (delayOrderAfterSetback == null) {
            delayOrderAfterSetback = new ArrayList<DelayOrderAfterSetback>();
        }
        return this.delayOrderAfterSetback;
    }

    /**
     * Gets the value of the runTime property.
     * 
     * @return
     *     possible object is
     *     {@link RunTime }
     *     
     */
    public RunTime getRunTime() {
        return runTime;
    }

    /**
     * Sets the value of the runTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link RunTime }
     *     
     */
    public void setRunTime(RunTime value) {
        this.runTime = value;
    }

    /**
     * Gets the value of the commands property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commands property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommands().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Commands }
     * 
     * 
     */
    public List<Commands> getCommands() {
        if (commands == null) {
            commands = new ArrayList<Commands>();
        }
        return this.commands;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnabled(String value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the forceIdleTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForceIdleTimeout() {
        return forceIdleTimeout;
    }

    /**
     * Sets the value of the forceIdleTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForceIdleTimeout(String value) {
        this.forceIdleTimeout = value;
    }

    /**
     * Gets the value of the idleTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdleTimeout() {
        return idleTimeout;
    }

    /**
     * Sets the value of the idleTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdleTimeout(String value) {
        this.idleTimeout = value;
    }

    /**
     * Gets the value of the ignoreSignals property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ignoreSignals property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIgnoreSignals().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIgnoreSignals() {
        if (ignoreSignals == null) {
            ignoreSignals = new ArrayList<String>();
        }
        return this.ignoreSignals;
    }

    /**
     * Gets the value of the javaOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaOptions() {
        return javaOptions;
    }

    /**
     * Sets the value of the javaOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaOptions(String value) {
        this.javaOptions = value;
    }

    /**
     * Gets the value of the logAppend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogAppend() {
        return logAppend;
    }

    /**
     * Sets the value of the logAppend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogAppend(String value) {
        this.logAppend = value;
    }

    /**
     * Gets the value of the mailXsltStylesheet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailXsltStylesheet() {
        return mailXsltStylesheet;
    }

    /**
     * Sets the value of the mailXsltStylesheet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailXsltStylesheet(String value) {
        this.mailXsltStylesheet = value;
    }

    /**
     * Gets the value of the minTasks property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinTasks() {
        return minTasks;
    }

    /**
     * Sets the value of the minTasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinTasks(BigInteger value) {
        this.minTasks = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrder(String value) {
        this.order = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priority property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPriority().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPriority() {
        if (priority == null) {
            priority = new ArrayList<String>();
        }
        return this.priority;
    }

    /**
     * Gets the value of the processClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessClass() {
        return processClass;
    }

    /**
     * Sets the value of the processClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessClass(String value) {
        this.processClass = value;
    }

    /**
     * Gets the value of the replace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplace() {
        return replace;
    }

    /**
     * Sets the value of the replace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplace(String value) {
        this.replace = value;
    }

    /**
     * Gets the value of the separateProcess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeparateProcess() {
        return separateProcess;
    }

    /**
     * Sets the value of the separateProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeparateProcess(String value) {
        this.separateProcess = value;
    }

    /**
     * Gets the value of the spoolerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpoolerId() {
        return spoolerId;
    }

    /**
     * Sets the value of the spoolerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpoolerId(String value) {
        this.spoolerId = value;
    }

    /**
     * Gets the value of the stopOnError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopOnError() {
        return stopOnError;
    }

    /**
     * Sets the value of the stopOnError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopOnError(String value) {
        this.stopOnError = value;
    }

    /**
     * Gets the value of the tasks property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTasks() {
        return tasks;
    }

    /**
     * Sets the value of the tasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTasks(BigInteger value) {
        this.tasks = value;
    }

    /**
     * Gets the value of the temporary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemporary() {
        return temporary;
    }

    /**
     * Sets the value of the temporary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemporary(String value) {
        this.temporary = value;
    }

    /**
     * Gets the value of the timeout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeout(String value) {
        this.timeout = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisible(String value) {
        this.visible = value;
    }

    /**
     * Gets the value of the warnIfLongerThan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarnIfLongerThan() {
        return warnIfLongerThan;
    }

    /**
     * Sets the value of the warnIfLongerThan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarnIfLongerThan(String value) {
        this.warnIfLongerThan = value;
    }

    /**
     * Gets the value of the warnIfShorterThan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarnIfShorterThan() {
        return warnIfShorterThan;
    }

    /**
     * Sets the value of the warnIfShorterThan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarnIfShorterThan(String value) {
        this.warnIfShorterThan = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="delay" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{}String">
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="error_count" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DelayAfterError {

        @XmlAttribute(required = true)
        protected String delay;
        @XmlAttribute(name = "error_count", required = true)
        protected BigInteger errorCount;

        /**
         * Gets the value of the delay property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDelay() {
            return delay;
        }

        /**
         * Sets the value of the delay property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDelay(String value) {
            this.delay = value;
        }

        /**
         * Gets the value of the errorCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getErrorCount() {
            return errorCount;
        }

        /**
         * Sets the value of the errorCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setErrorCount(BigInteger value) {
            this.errorCount = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="delay" type="{}Duration" />
     *       &lt;attribute name="is_maximum" type="{}Yes_no" />
     *       &lt;attribute name="setback_count" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DelayOrderAfterSetback {

        @XmlAttribute
        protected String delay;
        @XmlAttribute(name = "is_maximum")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String isMaximum;
        @XmlAttribute(name = "setback_count", required = true)
        protected BigInteger setbackCount;

        /**
         * Gets the value of the delay property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDelay() {
            return delay;
        }

        /**
         * Sets the value of the delay property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDelay(String value) {
            this.delay = value;
        }

        /**
         * Gets the value of the isMaximum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsMaximum() {
            return isMaximum;
        }

        /**
         * Sets the value of the isMaximum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsMaximum(String value) {
            this.isMaximum = value;
        }

        /**
         * Gets the value of the setbackCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSetbackCount() {
            return setbackCount;
        }

        /**
         * Sets the value of the setbackCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSetbackCount(BigInteger value) {
            this.setbackCount = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{}include"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Description {

        @XmlElementRef(name = "include", type = Include.class)
        @XmlMixed
        protected List<Object> content;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * {@link Include }
         * 
         * 
         */
        public List<Object> getContent() {
            if (content == null) {
                content = new ArrayList<Object>();
            }
            return this.content;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="exclusive" type="{}Yes_no" />
     *       &lt;attribute name="lock" use="required" type="{}String" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class LockUse {

        @XmlAttribute
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String exclusive;
        @XmlAttribute(required = true)
        protected String lock;

        /**
         * Gets the value of the exclusive property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExclusive() {
            return exclusive;
        }

        /**
         * Sets the value of the exclusive property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExclusive(String value) {
            this.exclusive = value;
        }

        /**
         * Gets the value of the lock property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLock() {
            return lock;
        }

        /**
         * Sets the value of the lock property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLock(String value) {
            this.lock = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}script"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{}Name" />
     *       &lt;attribute name="ordering" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "script"
    })
    public static class Monitor {

        @XmlElement(required = true)
        protected Script script;
        @XmlAttribute
        protected String name;
        @XmlAttribute
        protected BigInteger ordering;

        /**
         * Gets the value of the script property.
         * 
         * @return
         *     possible object is
         *     {@link Script }
         *     
         */
        public Script getScript() {
            return script;
        }

        /**
         * Sets the value of the script property.
         * 
         * @param value
         *     allowed object is
         *     {@link Script }
         *     
         */
        public void setScript(Script value) {
            this.script = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the ordering property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getOrdering() {
            return ordering;
        }

        /**
         * Sets the value of the ordering property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setOrdering(BigInteger value) {
            this.ordering = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="environment" type="{}environment" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="file" use="required" type="{}File" />
     *       &lt;attribute name="ignore_error" type="{}Yes_no" />
     *       &lt;attribute name="ignore_signal" type="{}Yes_no" />
     *       &lt;attribute name="log_file" type="{}File" />
     *       &lt;attribute name="param" type="{}String" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "environment"
    })
    public static class Process {

        protected Environment environment;
        @XmlAttribute(required = true)
        protected String file;
        @XmlAttribute(name = "ignore_error")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String ignoreError;
        @XmlAttribute(name = "ignore_signal")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String ignoreSignal;
        @XmlAttribute(name = "log_file")
        protected String logFile;
        @XmlAttribute
        protected String param;

        /**
         * Gets the value of the environment property.
         * 
         * @return
         *     possible object is
         *     {@link Environment }
         *     
         */
        public Environment getEnvironment() {
            return environment;
        }

        /**
         * Sets the value of the environment property.
         * 
         * @param value
         *     allowed object is
         *     {@link Environment }
         *     
         */
        public void setEnvironment(Environment value) {
            this.environment = value;
        }

        /**
         * Gets the value of the file property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFile() {
            return file;
        }

        /**
         * Sets the value of the file property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFile(String value) {
            this.file = value;
        }

        /**
         * Gets the value of the ignoreError property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIgnoreError() {
            return ignoreError;
        }

        /**
         * Sets the value of the ignoreError property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIgnoreError(String value) {
            this.ignoreError = value;
        }

        /**
         * Gets the value of the ignoreSignal property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIgnoreSignal() {
            return ignoreSignal;
        }

        /**
         * Sets the value of the ignoreSignal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIgnoreSignal(String value) {
            this.ignoreSignal = value;
        }

        /**
         * Gets the value of the logFile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogFile() {
            return logFile;
        }

        /**
         * Sets the value of the logFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogFile(String value) {
            this.logFile = value;
        }

        /**
         * Gets the value of the param property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParam() {
            return param;
        }

        /**
         * Sets the value of the param property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParam(String value) {
            this.param = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="directory" use="required" type="{}File" />
     *       &lt;attribute name="regex" type="{}String" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class StartWhenDirectoryChanged {

        @XmlAttribute(required = true)
        protected String directory;
        @XmlAttribute
        protected String regex;

        /**
         * Gets the value of the directory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDirectory() {
            return directory;
        }

        /**
         * Sets the value of the directory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDirectory(String value) {
            this.directory = value;
        }

        /**
         * Gets the value of the regex property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegex() {
            return regex;
        }

        /**
         * Sets the value of the regex property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegex(String value) {
            this.regex = value;
        }

    }

}
