//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.03 at 02:04:24 PM CEST 
//


package af.jstech.migration.jaxb.scheduler;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for Log_level.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Log_level">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="error"/>
 *     &lt;enumeration value="warn"/>
 *     &lt;enumeration value="info"/>
 *     &lt;enumeration value="debug"/>
 *     &lt;enumeration value="debug1"/>
 *     &lt;enumeration value="debug2"/>
 *     &lt;enumeration value="debug3"/>
 *     &lt;enumeration value="debug4"/>
 *     &lt;enumeration value="debug5"/>
 *     &lt;enumeration value="debug6"/>
 *     &lt;enumeration value="debug7"/>
 *     &lt;enumeration value="debug8"/>
 *     &lt;enumeration value="debug9"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum LogLevel {

    @XmlEnumValue("debug")
    DEBUG("debug"),
    @XmlEnumValue("debug1")
    DEBUG_1("debug1"),
    @XmlEnumValue("debug2")
    DEBUG_2("debug2"),
    @XmlEnumValue("debug3")
    DEBUG_3("debug3"),
    @XmlEnumValue("debug4")
    DEBUG_4("debug4"),
    @XmlEnumValue("debug5")
    DEBUG_5("debug5"),
    @XmlEnumValue("debug6")
    DEBUG_6("debug6"),
    @XmlEnumValue("debug7")
    DEBUG_7("debug7"),
    @XmlEnumValue("debug8")
    DEBUG_8("debug8"),
    @XmlEnumValue("debug9")
    DEBUG_9("debug9"),
    @XmlEnumValue("error")
    ERROR("error"),
    @XmlEnumValue("info")
    INFO("info"),
    @XmlEnumValue("warn")
    WARN("warn");
    private final String value;

    LogLevel(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LogLevel fromValue(String v) {
        for (LogLevel c: LogLevel.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
