//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.03 at 02:04:24 PM CEST 
//


package af.jstech.migration.jaxb.scheduler;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for When_holiday.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="When_holiday">
 *   &lt;restriction base="{}String">
 *     &lt;enumeration value="suppress"/>
 *     &lt;enumeration value="ignore_holiday"/>
 *     &lt;enumeration value="previous_non_holiday"/>
 *     &lt;enumeration value="next_non_holiday"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum WhenHoliday {

    @XmlEnumValue("ignore_holiday")
    IGNORE_HOLIDAY("ignore_holiday"),
    @XmlEnumValue("next_non_holiday")
    NEXT_NON_HOLIDAY("next_non_holiday"),
    @XmlEnumValue("previous_non_holiday")
    PREVIOUS_NON_HOLIDAY("previous_non_holiday"),
    @XmlEnumValue("suppress")
    SUPPRESS("suppress");
    private final String value;

    WhenHoliday(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WhenHoliday fromValue(String v) {
        for (WhenHoliday c: WhenHoliday.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
